--  7.Quel est le tarif de location moyen pour chaque genre ? (du plus élevé au plus bas) 
SELECT *
FROM category;
SELECT *
FROM film_category;
SELECT *
FROM film;
SELECT *
FROM language;
SELECT *
FROM film_actor;
SELECT *
FROM inventory;
SELECT *
FROM rental;
SELECT *
FROM payment;
SELECT *
FROM staff;
SELECT *
FROM actor;
SELECT *
FROM customer;
SELECT *
FROM address;
SELECT *
FROM city;
SELECT *
FROM country;
SELECT *
FROM store